// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsLoggedIn() {
  return window['go']['main']['Auth']['IsLoggedIn']();
}

export function Login() {
  return window['go']['main']['Auth']['Login']();
}

export function Register() {
  return window['go']['main']['Auth']['Register']();
}
